// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyamwgtjdvqgzljzxuua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95YW13Z3RqZHZxZ3psanp4dXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MjA2MjAsImV4cCI6MjA2ODk5NjYyMH0.cV9zP1ITlJRkFVywzMD3We08VUfclLMicwXsUk9HXCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});